-- Adminer 4.2.5 MySQL dump

SET NAMES utf8;
SET time_zone = '+00:00';
SET foreign_key_checks = 0;
SET sql_mode = 'NO_AUTO_VALUE_ON_ZERO';

DROP DATABASE IF EXISTS `oresto`;
CREATE DATABASE `oresto` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `oresto`;

DROP TABLE IF EXISTS `auth`;
CREATE TABLE `auth` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `key` varchar(255) NOT NULL,
  `date_created` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;

TRUNCATE `auth`;
INSERT INTO `auth` (`id`, `key`, `date_created`) VALUES
  (1,	'da39a3ee5e6b4b0d3255bfef95601890afd80709',	'2017-02-02 23:26:24'),
  (3,	'a1828bda5e8e36d885108a47b65dbaa583065ea6',	'2017-02-28 10:47:50');

DROP TABLE IF EXISTS `restaurants`;
CREATE TABLE `restaurants` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `city` varchar(255) NOT NULL,
  `postal_code` int(11) NOT NULL,
  `latitude` float DEFAULT NULL,
  `longitude` float DEFAULT NULL,
  `address` varchar(255) NOT NULL,
  `description` text NOT NULL,
  `image` varchar(255) DEFAULT NULL,
  `date_register` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=142 DEFAULT CHARSET=utf8;

TRUNCATE `restaurants`;
INSERT INTO `restaurants` (`id`, `name`, `city`, `postal_code`, `latitude`, `longitude`, `address`, `description`, `image`, `date_register`) VALUES
  (1,	'Crêperie Canaele',	'maule',	78580,	NULL,	NULL,	'18 Boulevard Paul Barre',	'Le restaurant vous accueille dans un cadre chaleureux où plusieurs petites salles vous permettent de passer un agréable moment tout en dégustant la cuisine au goût du jour d\'Hervé Klein.\r\nSituées sur plusieurs niveaux, les salles peuvent accueillir jusqu\'à 15 couverts',	'galette_complete_3.jpg',	'2017-01-06 01:30:50'),
  (78,	'O\'Tacos',	'Paris',	75020,	NULL,	NULL,	'91 Rue des Vignoles',	'Le restaurant vous accueille dans un cadre chaleureux où plusieurs petites salles vous permettent de passer un agréable moment tout en dégustant la cuisine au goût du jour d\'Hervé Klein.\r\nSituées sur plusieurs niveaux, les salles peuvent accueillir jusqu\'à 15 couverts',	'otacos.jpg',	'2017-01-10 10:36:44'),
  (79,	'Agapé',	'Paris',	75017,	NULL,	NULL,	'51 rue Jouffroy-d\'Abbans',	'Agapè... En Grèce ancienne, ce mot désignait l\'amour inconditionnel de l\'autre. Un nom qui augure des moments exclusifs, dans un décor chic et tendance, parfaitement adapté. La maison, hissée au rang de valeur sûre, compte une clientèle fidèle et conquise... Le fruit d\'un mariage réussi entre salle et cuisine. L\'accueil et le service se révèlent très professionnels, avec des conseils avisés sur le choix des mets et leur alliance avec les vins (plus de 600 références). La carte elle-même, assez courte, fait profession de transparence en mentionnant la provenance des produits, triés sur le volet. Il ne reste alors qu\'à se laisser bercer, en toute confiance, par une jolie romance : celle de la finesse des saveurs, de la justesse des assaisonnements, de la précision des cuissons... le tout porté au point subtil où l\'harmonie rencontre la surprise. L\'arme de séduction de l\'Agapé !',	'agape.jpg',	'2017-01-13 00:16:52'),
  (80,	'Le Vivarais',	'Lyon',	69002,	NULL,	NULL,	'1 place Gailleton',	'Avant 1789, le pays de Vivarais couvrait l\'actuelle Ardèche, au sud de Lyon ; plus de deux cents ans ont passé, mais ce terroir est toujours vivant ! Ici, le patron et sa fille cuisinent à quatre mains, proposant pâté en croûte maison, fond d\'artichaut des mères Lyonnaises au foie gras et quenelle sauce Nantua... Miam !',	'levivarais.jpg',	'2017-01-13 00:19:34'),
  (81,	'L\'Oiseau des Vignes',	'Beaune',	21200,	NULL,	NULL,	'31 Rue Jean Francois Maufoux',	'La griffe \"Loiseau\" (sous la houlette de la maison mère de Saulieu), une belle carte des vins - avec un choix rare de 70 vins au verre -, un lieu au cachet sûr (poutres, pierres) et surtout des assiettes pleines de caractère : une multitude d\'atouts pour cette bonne table au coeur de la gastronomie bourguignonne !',	'Loiseudesvignes.jpg',	'2017-01-13 00:21:51'),
  (82,	'France',	'Montmarault',	3390,	NULL,	NULL,	'1 rue Marx Dormoy',	'Le restaurant vous accueille dans un cadre chaleureux où plusieurs petites salles vous permettent de passer un agréable moment tout en dégustant la cuisine au goût du jour d\'Hervé Klein.\r\nSituées sur plusieurs niveaux, les salles peuvent accueillir jusqu\'à 15 couverts',	'france.jpg',	'2017-01-13 00:24:00'),
  (83,	'L\'Orangerie du Château',	'Blois',	41000,	NULL,	NULL,	'1 Avenue du Docteur Jean Laigret',	'Dans une dépendance du château (15e s.), avec une belle terrasse ouvrant sur le monument... L\'esprit de la Renaissance n\'est sans doute pas étranger à la cuisine, à la fois fine, légère et soignée.',	'blois.jpg',	'2017-01-13 00:26:24'),
  (84,	'L\'Assiette Champenoise',	'Tinqueux',	51430,	NULL,	NULL,	'40 av. Paul Vaillant-Couturier',	'À quoi reconnaît-on un grand cuisinier ? Au caractère de ses recettes, à sa capacité à apprivoiser même la simplicité, et bien sûr à révéler les saveurs... Ces qualités, Arnaud Lallement les possède toutes. Sans artifice, ses assiettes, rehaussées notamment de sauces magnifiques, réservent des émotions rares ! Le tout dans un cadre chic et moderne des plus agréables.',	'Champenoise.jpg',	'2017-01-13 00:42:00'),
  (85,	'Carré des Feuillants',	'Paris',	75001,	NULL,	NULL,	'14 rue de Castiglione',	'Il est rare qu\'un restaurant marie si parfaitement ambiance et style culinaire. Indéniablement, le Carré des Feuillants réussit cette osmose. Point d\'exubérance ou d\'élans démonstratifs, tout dans la mesure et la maîtrise : c\'est la première impression qui se dégage de cet ancien couvent (bâti sous Henri IV). Conçu par l\'artiste plasticien Alberto Bali, ami d\'Alain Dutournier - pour qui il a également signé les décors de ses Pinxo -, le décor n\'est que lignes épurées, presque minimalistes, et matériaux naturels, dans une veine contemporaine. Un cadre baigné de sérénité, pour un service impeccable et une cuisine à la hauteur. Marquée par la générosité et les racines landaises du chef, elle fait preuve de caractère et d\'inventivité. Composées à la manière d\'un triptyque - \"le basique, son complice végétal et le révélateur\" -, les assiettes ont l\'art de valoriser l\'authenticité du produit tout en sublimant le \"futile\". Quant à la cave, elle recèle de vrais trésors.',	'Feuillants.jpg',	'2017-01-13 00:49:03'),
  (86,	'Le Montaigu',	'Missillac',	44780,	NULL,	NULL,	'Domaine de la Bretesche',	'Arrivé en mars 2015, Thierry Karakachian met en valeur son expérience dans de belles tables de la côte d\'Azur - notamment Joël Robuchon et Yoshi à Monaco. Sa cuisine, parsemée de notes asiatiques, met joliment en valeur les nombreux produits du terroir breton. Un havre de gourmandise dans le magnifique domaine de la Bretesche !',	'Montaigu.jpg',	'2017-01-13 00:58:34'),
  (87,	'L\'Esprit de la Violette',	'Aix-en-Provence',	13100,	NULL,	NULL,	'10 Avenue de la Violette',	'Sur les hauteurs d\'Aix, l\'ancien Clos de la Violette a fait peau neuve ! Cette grande villa bourgeoise, dont le jardin est planté d\'arbres séculaires, est désormais le \"fief\" du chef Marc de Passorio : il décline ici une cuisine moderne et colorée, créative en diable, qui nous mène de belle surprise en belle surprise...',	'Violette.jpg',	'2017-01-13 01:01:21'),
  (88,	'Le Gindreau',	'Saint-Médard',	46150,	NULL,	NULL,	'D5',	'Une ancienne école de village transformée en restaurant. Derrière les fourneaux, Pascal Bardet - ancien d\'Alain Ducasse pendant 18 ans - signe une savoureuse cuisine contemporaine qui met en valeur les produits du terroir, et particulièrement la truffe, dont il est un vrai spécialiste ! Terrasse sous les marronniers.',	'Gindreau.jpg',	'2017-01-13 01:10:54'),
  (89,	'La Maison d\'à Côté',	'Montlivault',	41350,	NULL,	NULL,	'17 rue de Chambord',	'Le chef, Christophe Hay, a repris en 2014 cette maison à l\'atmosphère feutrée et contemporaine. Quelle réussite ! Tout y séduit : l\'accueil chaleureux - l\'équipe de cuisine n\'hésite pas à venir en salle pour présenter les plats -, la générosité des assiettes, leur créativité tout en subtilité, la beauté des produits régionaux...',	'Maison.jpg',	'2017-01-13 01:27:27'),
  (90,	'Loulou Côte Sauvage',	'Les Sables-d\'Olonne',	85100,	NULL,	NULL,	'19 route bleue',	'Ce Loulou-là a accroché sa jolie maison aux rochers de la côte sauvage, face à la mer : la vue est imprenable ! Ici, les produits iodés - extrafrais - sont évidemment à l\'honneur : homards tirés du vivier, poissons achetés directement à la criée des Sables... pour des plats savoureux et bien tournés.',	'Olonne.jpg',	'2017-01-13 01:29:37'),
  (91,	'L\'Almandin',	'Saint-Cyprien',	66750,	NULL,	NULL,	'Boulevard de l\'Almandin',	'Au bord de la Méditerranée, dans un cadre contemporain, cette table joue l\'inédit autour d\'une cuisine qui prend les papilles par surprise avec de beaux mélanges sucré-salé. La sole juste snakée, crème de maïs et charlotte courgettes-ananas, en est un bon exemple... L\'originalité au pouvoir !',	'Almandin.jpg',	'2017-01-13 01:39:33'),
  (92,	'La Côte Saint-Jacques',	'Joigny',	89300,	NULL,	NULL,	'14 fg de Paris',	'D\'une petite couturière audacieuse à son petit-fils globe-trotter, la Côte St-Jacques s\'est imposée comme une institution de la gastronomie bourguignonne ! La noblesse des produits, la générosité des assiettes, le caractère intemporel de certaines recettes : une histoire culinaire écrite au fil de l\'Yonne toute proche...',	'Jacques.jpg',	'2017-01-13 01:41:38'),
  (93,	'L\'Atelier du Parc',	'Paris',	75015,	NULL,	NULL,	'35 Boulevard Lefebvre',	'Voilà un établissement qui tranche avec les nombreuses brasseries traditionnelles de la porte de Versailles : bar en plexiglas changeant de couleur, teintes sobres et beaux sièges design qui donnent leur version d\'un nouvel Art déco... Ce cadre chic et moderne sied parfaitement à la cuisine inventive et soignée d\'un jeune chef plein d\'allant. Les suggestions du jour sont annoncées de vive voix à la clientèle, et les plats de la carte sont renouvelés régulièrement. Saumon mi-fumé par nos soins, poutargue et sorbet granny smith ; épaule d\'agneau confite 36 heures aux épices ; entremet noix de coco et pistache, sorbet griotte... Tout est fait maison ! Beaucoup de finesse, de la créativité et une belle surprise, juste en face au parc des expositions.',	'Parc.jpg',	'2017-01-13 01:43:37'),
  (94,	'Mirazur',	'Menton',	6500,	NULL,	NULL,	'30 avenue Aristide-Briand',	'Un lieu d\'exception ! C\'est d\'abord un bel écrin, perché sur la corniche, grand ouvert sur l\'azur de la Méditerranée et du ciel... C\'est surtout une table excellente, portée par un chef inspiré : l\'Argentin Mauro Colagreco signe un hymne unique aux plantes aromatiques, aux fleurs, aux légumes de son potager, aux agrumes, etc. Les saisons, la région sont illuminées.',	'Mirazur.jpg',	'2017-01-13 01:45:13'),
  (95,	'Maison Blanche',	'Paris',	75008,	NULL,	NULL,	'Avenue Montaigne',	'Un cadre grandiose ! Tel un cube posé sur le toit du théâtre des Champs-Élysées - un pont suspendu soutient cette étonnante Maison perchée -, la salle semble toiser la capitale à travers son immense baie vitrée... Quant à la terrasse, elle offre une vue tout simplement époustouflante sur la tour Eiffel. Si bien qu\'on ne sait plus où poser le regard en entrant dans ce loft ultradesign ! Lové dans l\'une des banquettes-alcôves ou installé sur la mezzanine, on ne se lasse pas du spectacle... Côté carte : une cuisine contemporaine bien réalisée, imprégnée d\'influences méditerranéennes, et de l\'âme voyageuse du chef. Avec une belle sélection de vins venus du Languedoc et de la vallée du Rhône... juste là-bas, derrière les toits de Paris.',	'Blanche.jpg',	'2017-01-13 01:46:26'),
  (96,	'Le Jules Verne',	'Paris',	75007,	NULL,	NULL,	'2ème étage Tour Eiffel',	'Sans vous sentir obligé de gravir les 704 marches qui conduisent au 2e étage de la tour Eiffel, rendez-vous au pilier sud et laissez faire l\'ascenseur privé qui mène directement au Jules Verne, à 125 m au-dessus du sol. Ce lieu emblématique dirigé par Alain Ducasse offre un cadre unique : le midi comme le soir, la vue sur Paris à travers les poutrelles métalliques de la tour est tout simplement spectaculaire ! Pensez à réserver très à l\'avance (uniquement par Internet) votre table près des baies vitrées. Le décor contemporain signé Patrick Jouin (parois en nid-d\'abeilles, fauteuils en cuir et fibre de carbone) est à la hauteur, de même que la cuisine classique revisitée façon Ducasse, réalisée ici par le chef Éric Azoug. Les pâtisseries sont quant à elles signées Christophe Devoille, pâtissier-chocolatier et glacier de formation. Enfin, la carte des vins, remarquable, compte plus de 400 références de l\'Hexagone, dont quelques crus d\'exception. Une adresse au sommet du patrimoine français !',	'5988_1.jpg',	'2017-02-23 15:59:41'),
  (97,	'La Tour d\'Argent',	'Paris',	75005,	NULL,	NULL,	'15 quai de la Tournelle',	'Une demeure historique liée depuis 1912 à la famille Terrail : André, le fondateur, son fils Claude, et à présent son petit-fils, André. Pour autant, la \"saga\" de la Tour d\'Argent débuta bien avant. Déjà en 1582, l\'enseigne signalait une élégante auberge, qui devint un restaurant en 1780. Mais la légende commence véritablement au début du 20e s. lorsque Terrail l\'achète, avec cette idée de génie dans la tête : élever l\'immeuble d\'un étage pour y installer la salle à manger, et jouir ainsi d\'un panorama unique sur la Seine et Notre-Dame. Le cadre cossu a conservé son lustre d\'antan. Le service, parfaitement réglé, assure toujours le spectacle, dont le fameux rituel du canard de Challans au sang, inventé en 1890 par Frédéric Delair. L\'emblème d\'un classicisme indétrônable, mais nullement figé : véritable palimpseste, la carte conserve la mémoire de plusieurs décennies de haute gastronomie française - sans s\'interdire des incursions vers la modernité. Quant à l\'extraordinaire cave du sommelier David Ridgway, elle renfermerait... près de 500 000 bouteilles !',	'tourdargent.jpg',	'2017-02-23 15:59:45'),
  (98,	'Relais Louis XIII',	'Paris',	75006,	NULL,	NULL,	'8 rue des Grands-Augustins',	'Une table chargée d\'histoire, bâtie sur les caves de l\'ancien couvent des Grands-Augustins : c\'est ici que, le 14 mai 1610, une heure après l\'assassinat de son père Henri IV, Louis XIII apprit qu\'il devrait désormais régner sur la France... La salle à manger semble se souvenir de ces grandes heures du passé : colombages, pierres apparentes, boiseries, vitraux et tentures, tout distille un charme d\'autrefois, avec çà et là des objets de collection (tableaux)... Une atmosphère toute particulière, donc, comme hors du temps, particulièrement propice à la découverte de la cuisine du chef, Manuel Martinez, tenante d\'un noble classicisme culinaire. Après un joli parcours chez Ledoyen, au Crillon, à la Tour d\'Argent, ce Meilleur Ouvrier de France a décidé de s\'installer en ce Relais pour y perpétuer la tradition. Quoi de plus logique ? L\'histoire continue donc et les habitués sont nombreux, plébiscitant notamment la formule déjeuner, d\'un excellent rapport qualité-prix !',	'louis13.jpg',	'2017-02-23 15:59:46'),
  (99,	'Saturne',	'Paris',	75002,	NULL,	NULL,	'17 rue N.-D.-des-Victoires',	'Saturne : dieu de l\'agriculture et anagramme de \"natures\"... Une bien jolie enseigne, qui dit tout : le chef, Sven Chartier, formé auprès d\'Alain Passard à l\'Arpège (7e arrondissement), et son associé, Ewen Le Moigne, sommelier de son état, partagent l\'amour du bon produit. Vins naturels, petits producteurs, respect des saisons : Saturne compile tout cela, et bien plus encore ! Huître et maquereau au jus de maïs acidulé ; merlan de ligne, moules, fenouil et eau de tomate ; agneau à l\'artichaut, citronnelle, compote d\'oignons et mozzarella fumée... Les assiettes sont pleines de saveurs, les accords mets-vins harmonieux... Quant à l\'atmosphère, résolument moderne, elle affirme fièrement ses influences scandinaves (mobilier en bois blond, béton ciré). Oui, on peut faire branché et savoureux !',	'saturne.jpg',	'2017-02-23 15:59:47'),
  (100,	'Le Bouche à Oreille',	'Boutervilliers',	91150,	NULL,	NULL,	'11 rue de la Chapelle',	'Un intérieur moderne, dont les murs portent de beaux épis de blé en hommage à la campagne environnante... Mais surtout, les assiettes d\'Aymeric Dreux, qui portent la gourmandise à une autre dimension : précises et maîtrisées, elles mettent en valeur de beaux produits dans toute la force de leur goût.',	'bouche.jpg',	'2017-02-23 15:59:47'),
  (101,	'Loulou Côte Sauvage',	'Les Sables-d\'Olonne',	85100,	NULL,	NULL,	'19 route bleue',	'Ce Loulou-là a accroché sa jolie maison aux rochers de la côte sauvage, face à la mer : la vue est imprenable ! Ici, les produits iodés - extrafrais - sont évidemment à l\'honneur : homards tirés du vivier, poissons achetés directement à la criée des Sables... pour des plats savoureux et bien tournés.',	'loulou.jpg',	'2017-03-05 18:55:24'),
  (102,	'Le Sénéchal',	'Sauveterre-de-Rouergue',	12800,	NULL,	NULL,	'Sauveterre de Rouergue',	'En vous accueillant au Sénéchal, je voudrais vous faire partager ma sensibilité, ma personnalité, mon attachement aux produits et aux producteurs, à la nature et aux saisons, à mon village. Ne m’en voulez pas si quelques fois au détour d’un menu il m’arrive de changer l’ordre établi ou une partie de la recette, c’est un peu ma nature... Ma cuisine est comme Sauveterre, un refuge où authenticité, humilité, émotions et simplicité sont les principaux ingrédients.',	'lesenegale.jpg',	'2017-03-05 18:55:31'),
  (103,	'Auberge des Deux Magots',	'La Roche-Bernard',	56130,	NULL,	NULL,	'1 Place du Bouffay',	'Natif du centre Bretagne,je mets un point d\'honneur à travailler des produits frais et issus de producteurs locaux.',	'auberge.jpg',	'2017-03-05 18:55:38'),
  (104,	'Le Bréard',	'Honfleur',	14600,	NULL,	NULL,	'7 rue du Puits',	'Cadre contemporain et cuisine subtile au menu de ce restaurant, situé dans une ruelle pavée proche de l\'église Ste-Catherine. Le chef associe de belles saveurs avec créativité : en témoigne ce cabillaud cuit à basse température, accompagné d\'un risotto au combava... Beaucoup de fraîcheur et de générosité !',	'lebreard.jpg',	'2017-03-05 18:55:48'),
  (105,	'Auberge du Bon Laboureur',	'Chenonceaux',	37150,	NULL,	NULL,	'6 rue Dr Bretonneau',	'Je privilégie la véritable cuisine traditionnelle française revisitée au goût du jour.',	'aubergedubonlaboureur.jpg',	'2017-03-05 18:56:29'),
  (106,	'Maison Decoret',	'Vichy',	3200,	NULL,	NULL,	'15 rue du Parc',	'Une bâtisse du 19es., une grande véranda cubique jouant sur la transparence : tel est le décor voulu par Jacques Decoret. Recherche esthétique et finesse sont au rendez-vous dans l\'assiette, autour de très beaux produits. Et quelques chambres style maison d\'hôtes rappelle l\'esprit contemporain du lieu.',	'maisondecoret.jpg',	'2017-03-05 18:55:55'),
  (107,	'Monsieur Jean',	'Lille',	59000,	NULL,	NULL,	'12 rue de Paris',	'Façade flamande, magnifique escalier, mur en brique orné de sculptures en pierre : une demeure au puissant charme du Nord... C\'est l\'adresse lilloise de Marc Meurin (doublement étoilé à Busnes), dans laquelle on savoure de belles recettes actuelles, travaillées avec soin et joliment présentées. Très recommandable !',	'monsieurjean.jpg',	'2017-03-05 18:56:00'),
  (108,	'Paul Bocuse',	'Collonges-au-Mont-d\'Or',	69660,	NULL,	NULL,	'40 Rue de la Plage',	'Temple de la grande cuisine, institution du service à l\'ancienne... Le restaurant de Paul Bocuse est un véritable monument. Classique parmi les classiques, chaque assiette incarne l\'une des plus belles pages de la gastronomie française. Le grand chef est entré dans l\'Histoire : quel meilleur hommage que ces trois étoiles portées depuis 1965 !',	'paulbocuse.jpg',	'2017-03-05 18:56:04'),
  (109,	'L\'Ortensia',	'Saint-Gervais-sur-Mare',	34610,	NULL,	NULL,	'2 rue du château',	'Lui manque-t-il un \"h\" ? Non : c\'est ainsi que l\'on orthographie cette plante en occitan ! Créé dans une ancienne pépinière, le restaurant séduit grâce à une cuisine inventive qui met à l\'honneur les viandes et légumes issus des fermes environnantes. L\'accueil est fort chaleureux : décidément, une fleur très séduisante !',	'lortensia.jpg',	'2017-03-05 18:56:09'),
  (110,	'La Table de Patrick Raingeard',	'Èze-Bord-de-Mer',	6360,	NULL,	NULL,	'1312 avenue Raymond-Poincaré',	'Dans le cadre luxueux de l\'hôtel Cap Estel, cerné par la mer, Patrick Raingeard rend un bel hommage à la Méditerranée et ses rives : la qualité des produits, l\'exécution soignée, la pointe d\'inventivité qui rehausse l\'ensemble, tout invite à un repas privilégié...',	'latabledepatrickraingeard.jpg',	'2017-03-05 18:56:13'),
  (111,	'Fanny Rey et Jonathan Wahid',	'Saint-Rémy-de-Provence',	13210,	NULL,	NULL,	'12 Boulevard Mirabeau',	'Fanny Rey, finaliste de Top Chef 2011, est aux fourneaux de cette vénérable Auberge et décline une savoureuse cuisine du marché, mettant superbement en valeur les produits des Alpilles. À ses côtés, on trouve nul autre que... Jonathan Wahid, son compagnon, pâtissier émérite et ancien champion de France du dessert. Un duo de choc !',	'fannyreyetjonathanwahid.jpg',	'2017-03-05 18:56:18'),
  (112,	'Le Diapason',	'Avignon',	84000,	NULL,	NULL,	'1764 avenue du Moulin-Notre-Dame - BX',	'Mon amour de la Cuisine Moderne et Gastronomique Traditionnel donne le ton au Restaurant le Diapason. J\'aime valoriser les richesses de notre Vallis Clausa (Vaucluse), véritable potager de la France et ainsi mettre en avant nos producteurs locaux. Réussir à sublimer les produits de saison, telle est la philosophie de ma cuisine.',	'lediapason.jpg',	'2017-03-05 18:56:22'),
  (113,	'L\'Atelier de Marc Meurin',	'Lens',	62300,	NULL,	NULL,	'97 Rue Paul Bert',	'Étonnant, le bâtiment dessine un cercle tout en verre : son architecture se marie parfaitement au Louvre-Lens voisin ! Loin d\'être un simple restaurant de musée, cet Atelier confié aux bons soins de Marc Meurin, fameux chef étoilé de Busnes, met à l\'honneur les produits de la région. Tout indiqué en cas de visite...',	'atelier_marc_meudin.jpg',	'2017-03-07 00:43:41'),
  (114,	'Le Relais Bernard Loiseau',	'Saulieu',	21210,	NULL,	NULL,	'2 rue d\'Argentine',	'L\'élégant cadre bourguignon, ouvert sur le jardin, est toujours aussi séduisant. La carte offre le choix entre les \"classiques de Bernard Loiseau\" et des propositions plus actuelles, imaginées par le chef Patrick Bertron. Quant au service, aimable et efficace, il ajoute encore au plaisir du repas !',	'relais_bernard_loiseau.jpg',	'2017-03-07 00:43:58'),
  (115,	'William Frachot',	'Dijon',	21000,	NULL,	NULL,	'5 rue Michelet',	'Un décor contemporain qui puise aux sources de la nature, très minéral et très végétal, orné notamment de troncs d\'arbre... Un bel écrin pour la cuisine de William Frachot, éprise d\'essentiel, inspirée, voyageuse et aboutie. Écorce des saveurs, saveurs corsées !',	'william_frachot.jpg',	'2017-03-07 00:44:09'),
  (116,	'Le Millénaire',	'Reims',	51000,	NULL,	NULL,	'4 rue Bertin',	'Non loin de la place Royale, une table d\'une prestance toute contemporaine, associant tons crème, chêne clair et lignes élégantes. Une véritable invitation à découvrir cette cuisine réalisée à quatre mains (père et fils), bien ancrée dans le siècle... et dans le Millénaire !',	'millenaire.jpg',	'2017-03-07 00:44:15'),
  (117,	'La Poule Noire',	'Marseille',	13001,	NULL,	NULL,	'61 Rue Sainte',	'La Poule noire se mérite ! Dissimulée derrière une étroite entrée, ce restaurant, fréquenté par les habitués, joue la fraîcheur et la nouveauté (le menu du jour change quotidiennement). La surprise des propriétaires, Sophie et Frank ? Une élégante mini-terrasse de douze places, habillée de bois clair.',	'poule_noire.jpg',	'2017-03-07 00:44:20'),
  (118,	'Jacques Faussat',	'Paris',	75017,	NULL,	NULL,	'54 rue Cardinet',	'Un petit bout de province à Paris, cela paraît impossible. C\'est pourtant la gageure que relève le chef de ce restaurant du quartier des Ternes, gersois et fier de l\'être. Jacques Faussat n\'aime rien tant que la simplicité inspirée de ses racines et de son enfance. Une simplicité également apprise auprès de Michel Guérard et surtout d\'Alain Dutournier - sa rencontre avec cet homme de passion qui partage les mêmes origines sera déterminante dans sa carrière, à commencer par dix années passées aux fourneaux du Trou Gascon. Avec quelques réminiscences du Sud-Ouest, sa cuisine joue donc surtout la carte de la générosité et des saveurs, misant tout sur de bons produits travaillés pour en faire ressortir... le meilleur. Un bon rapport qualité-prix.',	'jacques_faussat.jpg',	'2017-03-07 00:44:26'),
  (119,	'Auberge du Vieux Puits',	'Fontjoncouse',	11360,	NULL,	NULL,	'5 Avenue Saint-Victor',	'Le produit est la star de cette cuisine ludique et inspirée, qui porte certaines émotions gustatives à l\'incandescence. Saisons, terroir, invention : Gilles Goujon excelle dans l\'équilibre des saveurs et la maîtrise des techniques culinaires ; il s\'est, en outre, entouré d\'une équipe efficace et proche du client.',	'vieux_puits.jpg',	'2017-03-07 00:47:31'),
  (120,	'La Table du Lancaster',	'Paris',	75008,	NULL,	NULL,	'7 rue de Berri',	'Toute l\'atmosphère exclusive et confidentielle d\'un restaurant de grand hôtel - et quand il s\'agit du Lancaster, ce mythique établissement au charme si particulier... Le chef signe dans ce cadre une cuisine étonnante, tout en présentations soignées et en jeux de textures, concoctée avec la complicité de beaux produits. Ses assiettes révèlent une large palette d\'expression, mettant aussi bien en valeur les terroirs, les marées que les influences lointaines. Ou comment revisiter la gastronomie française tout en redessinant une géographie des saveurs ! Dernier conseil : aux beaux jours, n\'hésitez pas à profiter de la terrasse aménagée dans la cour-jardin, à l\'abri des regards.',	'lancaster.jpg',	'2017-03-07 00:49:30'),
  (121,	'Porte Guillaume',	'Dijon',	21000,	NULL,	NULL,	'2 Rue de la Liberté',	'Une table de tradition chaleureuse et accueillante. Au menu, donc : oeufs en meurette, coq au vin, poire pochée à la vanille... L\'adresse abrite également un caveau voûté en guise de bar à vins, qui ravira les amateurs de bourgogne.',	'porte_guillaume.jpg',	'2017-03-07 00:53:30'),
  (122,	'Shang Palace',	'Paris',	75016,	NULL,	NULL,	'10 Avenue d\'Iéna',	'Shangri-La... Le nom résonne comme un voyage aux confins de l\'Asie, vers un paradis luxueux et imaginaire. Le célèbre hôtel parisien, né en 2010, a su donner le même éclat à ses restaurants, dont ce Shang Palace. Situé au niveau inférieur de l\'établissement, il transporte ses hôtes dans un Hong Kong merveilleux, entre raffinement extrême-oriental et élégance Art déco. Colonnes incrustées de jade, paravents sculptés et lustres en cristal promettent un dîner aussi feutré qu\'étincelant. La cuisine cantonaise est à l\'honneur ; on peut partager en toute convivialité un assortiment de plats servis au centre de la table. Les cuissons se révèlent précises, les parfums subtils. Les dim sum sont moelleux à souhait et le goût de la sole cuite à la vapeur s\'envole accompagné de champignons noirs et de tofu soyeux. Pour finir, entre autres douceurs, une crème de mangue, garnie de pomélo et de perles de sagou, laisse une belle impression de fraîcheur...',	'shang_palace.jpg',	'2017-03-07 01:04:07'),
  (123,	'La Baratte',	'Tourcoing',	59200,	NULL,	NULL,	'395 rue du Clinquet',	'Une petite maison en briques dans un quartier résidentiel de Tourcoing. Surprise à l\'intérieur : on découvre une salle résolument contemporaine et élégante, avec une agréable vue sur le jardin et sa terrasse en teck. Côté cuisine, le chef fait montre d\'inventivité... pour le bonheur du produit frais !',	'baratte.jpg',	'2017-03-07 01:03:52'),
  (124,	'Le Clos St-Basile',	'Mougins',	6250,	NULL,	NULL,	'351 avenue St-Basile',	'Nouveau départ en 2014 pour ce restaurant, avec l\'arrivée d\'un couple aussi professionnel que dynamique. Le chef excelle dans la confection d\'une cuisine du marché savoureuse et inventive ; la patronne, sommelière, a d\'excellents vins à vous conseiller. Enfin, la belle terrasse est idéale pour les beaux jours !',	'stbasile.jpg',	'2017-03-07 01:09:33'),
  (125,	'Meurin',	'Busnes',	62350,	NULL,	NULL,	'1098 Rue de Lillers',	'Moment de haute gastronomie dans le décor chic et feutré du Château de Beaulieu... Marc Meurin signe une cuisine d\'excellente facture, fine et inventive. Bouillons, jus, produits, accords de saveurs, etc. Chaque assiette est un plaisir.',	'meurin.jpg',	'2017-03-07 01:13:00'),
  (126,	'La Table des Merville',	'Castanet-Tolosan',	31320,	NULL,	NULL,	'3 place Richard',	'Une extension tout en verre sur une jolie place avec terrasse, des cuisines ouvertes sur la salle donnant l\'impression que le chef travaille parmi les clients : Claudie et Thierry Merville ont su créer un lieu original... Et les assiettes, aussi joliment contemporaines et soignées, dégagent ce même parfum de \"Mervilleux\" !',	'merville.jpg',	'2017-03-07 01:15:32'),
  (127,	'Le 39V',	'Paris',	75008,	NULL,	NULL,	'39 Avenue George V',	'La température monte au 39... de l\'avenue George-V ! Franchissez donc le porche de ce discret immeuble haussmannien : de là, un ascenseur vous mène directement au 6e étage. Dans les hauteurs, sur les toits de Paris, niche cette petite cité pour gastronomes... D\'abord le bar, habillé de noir, où l\'on peut siroter quelque cocktail avant de rejoindre sa table. Puis la grande salle, coiffée de verre et dont les larges baies ouvrent sur une délicieuse petite terrasse. Les lieux sont raffinés ; l\'assiette n\'est pas en reste. Le chef, Frédéric Vardon, propose une belle relecture de la cuisine de tradition. Très attaché à la qualité des ingrédients, il met un point d\'honneur à rendre visite à ses fournisseurs sur leur domaine de production. Un travail aux origines et une véritable clef de voûte pour des assiettes raffinées et démontrant de solides bases classiques. On s\'enfièvre pour ce 39V plein de saveurs !',	'39v.jpg',	'2017-03-07 01:17:35'),
  (128,	'Le Pré Catelan',	'Paris',	75016,	NULL,	NULL,	'Route de la Grande Cascade',	'Une enclave enchantée au coeur du bois de Boulogne, tel est Le Pré Catelan. Somptueux et chargé d\'histoire, le lieu dévoile un décor de jardins et d\'architectures classiques. Pierre-Yves Rochon a révolutionné l\'esprit du pavillon Napoléon III en le parant d\'un mobilier design et de tons vert, blanc et argent, tandis que l\'orangerie attenante livre un cadre contemporain à la verdure qui l\'entoure... C\'est dans ce cadre rêvé que l\'on peut déguster depuis quelques années la cuisine savoureuse et inventive de Frédéric Anton. Ce Meilleur Ouvrier de France révèle son talent à travers une carte alliant équilibre, harmonie et générosité. Pour chaque assiette, il recherche la perfection, soignant jusqu\'à la composition graphique. La précision et la rigueur transmises par ses mentors (dont Robuchon) sont sa signature, ainsi que son goût pour les associations inédites et la vraie nature des produits. Le tout sublimé par une cave prestigieuse et un accueil irréprochable. Autant d\'arguments en faveur de cette noble maison aux murs d\'argent et... aux plats d\'or.',	'pre_catelan.jpg',	'2017-03-07 01:20:09'),
  (129,	'Le Fanal',	'Banyuls-sur-Mer',	66650,	NULL,	NULL,	'17 Avenue du Fontaulé',	'Juste devant le port de Banyuls, laissez-vous guider par les lumières de ce Fanal ! Pascal Borrell y signe des recettes créatives et épurées, pleines de relief, qui s\'appuyent sur des produits de première fraîcheur : le matin, les poissons sont livrés encore vivants en cuisine... À découvrir d\'urgence.',	'fanal.jpg',	'2017-03-07 01:22:29'),
  (130,	'MaSa',	'Boulogne-Billancourt',	92100,	NULL,	NULL,	'112 avenue Victor-Hugo',	'Ne soyez pas surpris en vous asseyant : ici, il n\'y a pas de carte, et les menus n\'indiquent pas les plats... Mais si on vous laisse dans l\'expectative, c\'est pour mieux vous séduire ensuite ! Avec de très beaux produits (oeuf de Marans, boeuf de Coutancie, canette de Challans) et au gré des arrivages quotidiens, le chef réalise une cuisine ludique et inspirée, n\'hésitant pas à jouer la carte de la surprise au détour d\'une recette. Les préparations sont légères et bien équilibrées ; on les accompagne d\'une jolie sélection de vins au verre. Un mot enfin sur le décor contemporain, repensé dans des tons noir et blanc, et sur l\'agréable terrasse arborée, à l\'arrière, au calme.',	'masa.jpg',	'2017-03-07 01:24:11'),
  (131,	'Le Restaurant',	'Paris',	75006,	NULL,	NULL,	'13 rue des Beaux-Arts',	'Le Restaurant de l\'Hôtel n\'a rien d\'une table gastronomique conventionnelle. Il doit son atmosphère baroque, anachronique et éclectique au designer Jacques Garcia, adepte du style Empire revisité. Dans un esprit salon privé, le décor rivalise de drapés, banquettes et fauteuils bas, alcôves, moulures dorées et tons fauves, tel un tableau d\'Ingres dans sa période orientaliste. Un peu trop chargé pour certains, dépaysant pour d\'autres, en tout cas original ! Le tout agrémenté d\'une ravissante cour intérieure où la terrasse et la fontaine font oublier que l\'on se trouve au coeur de Paris. Pour satisfaire les exigences de sa clientèle de \"happy few\" - people et stars sensibles à son intimité et à ses hôtes illustres (Oscar Wilde, Borges, etc.) -, il fallait tout le savoir-faire d\'un jeune chef au beau parcours. Autrefois second et seul aux commandes depuis 2011, ce dernier travaille d\'excellents produits et aime revisiter les classiques de la gastronomie française ; son épouse Johanna, chef-pâtissière, se charge avec brio de la conclusion des repas. Un duo gagnant !',	'LE_restaurant.jpg',	'2017-03-07 01:26:18'),
  (132,	'Le Domaine du Colombier',	'Malataverne',	26780,	NULL,	NULL,	'270 Chemin de Malombre',	'Sur les ruines d\'un hermitage monastique, on aime s\'installer dans les salles en enfilade - voûtées, à la décoration soignée - et sur l\'apaisante terrasse de ce restaurant. La cuisine, fine et ancrée dans son époque, révèle des cuissons millimétrées et une technique solide : nos papilles sont ravies !',	'domaine_colombier.jpg',	'2017-03-07 01:29:55'),
  (133,	'Domaine des Séquoias',	'Ruy',	38300,	NULL,	NULL,	'54 Vie-de-Boussieu',	'On passe un agréable moment au sein de cette belle maison de maître, d\'une élégance toute classique, où de grandes toiles contemporaines projettent leurs couleurs à travers la pièce. Le repas se décline au fil de mets très savoureux et originaux, guidés par le souci du bon produit. Autre atout : l\'accueil est charmant.',	'domaine_sequoias.jpg',	'2017-03-07 01:32:29'),
  (134,	'Graindorge',	'Paris',	75017,	NULL,	NULL,	'15 rue de l\'arc de triomphe',	'Le climat de l\'Étoile réussit plutôt bien à Bernard Broux, sans doute parce qu\'il a su adapter au goût parisien ce qui fait le charme des auberges de son \"Ch\'Nord\" natal ! Dans la salle d\'esprit Art déco, on s\'attable volontiers devant un potjevlesch, des bintjes farcies à la brandade de morue, un waterzoï de la mer aux crevettes grises d\'Ostende ou encore l\'incontournable lièvre à la flamande pendant la saison de la chasse... De généreuses recettes flamandes, donc, complétées de suggestions du marché. Le tout se déguste avec de belles bières artisanales d\'outre-Quiévrain (Angélus, Moinette Blonde), mais que les amateurs de vin se rassurent, ils trouveront aussi leur bonheur !',	'graindorge.jpg',	'2017-03-07 01:33:52'),
  (135,	'Le Taillevent',	'Paris',	75008,	NULL,	NULL,	'15 Rue Lamennais',	'Cette adresse qu\'on ne présente plus porte fièrement les couleurs de la tradition. Par ses propriétaires, en premier lieu : la famille Vrinat qui, depuis trois générations, a fait la réputation de ce restaurant incontournable et est désormais associée à la famille Gardinier (Les Crayères à Reims). Par son nom : référence à l\'auteur du \"Viandier\", le plus ancien manuscrit de recettes rédigé en français (vers 1379). Par son cadre, enfin : l\'ancien hôtel particulier du duc de Morny (19e s.), classique, feutré et propice aux rendez-vous politiques et aux repas d\'affaires. L\'éclairage tamisé et l\'harmonie de tons bruns, rouges et beiges favorisent un climat d\'intimité, enrichi depuis 2004 par des oeuvres d\'art contemporain. Une façon d\'entretenir des liens avec l\'air du temps. Comme en cuisine, où le sixième chef de la maison, Alain Solivérès, mêle l\'ancien au moderne, les recettes empruntées à la haute gastronomie à des touches méditerranéennes et actuelles. Et, cerise sur le gâteau : les caves, pléthoriques en vins rares, qui comptent parmi les plus belles de la capitale.',	'Taillevent.jpg',	'2017-03-07 01:35:16'),
  (136,	'Le Chiberta',	'Paris',	75008,	NULL,	NULL,	'3 Rue Arsène Houssaye',	'Le Chiberta version Guy Savoy s\'est choisi le noir comme couleur, le vin comme symbole et l\'inventivité comme fil conducteur. En entrant, on est plongé dans un autre univers, tamisé, calme et feutré. Parfait pour les repas d\'affaires comme pour les rencontres plus intimes. L\'aménagement intérieur, conçu par l\'architecte Jean-Michel Wilmotte, surprend par son minimalisme radical, tout en chic discret et design. La grande originalité du lieu reste indéniablement la \"cave à vins verticale\" : de grands crus habillant les murs à la manière d\'une bibliothèque ou d\'oeuvres d\'art. Entre deux alignements de bouteilles, des tableaux modernes et abstraits colorent ponctuellement l\'espace. Confortablement installé à table, on apprécie toute l\'étendue de la cuisine, supervisée par le \"patron\", qui revisite joliment la tradition. Bon à savoir : le menu du marché est revu chaque semaine, une carte d\'huîtres est disponible au comptoir, et la cave, évidemment, est parfaitement composée.',	'chiberta.jpg',	'2017-03-07 01:36:24'),
  (137,	'Restaurant du Palais Royal',	'Paris',	75001,	NULL,	NULL,	'110 Galerie de Valois',	'C\'est dans le cadre idyllique des jardins du Palais Royal, à deux pas du ministère de la Culture, qu\'on trouve cet élégant restaurant qui ne cache pas ses ambitions gastronomiques. Aux fourneaux officie le jeune chef grec Philip Chronopoulos, qui fut notamment chef exécutif de l\'Atelier de Joël Robuchon-Étoile. Avec de superbes produits, il signe ici une cuisine créative, percutante, se fendant de recettes d\'une vivifiante maturité - en témoignent ces langoustines justes saisies, girolles et amandes fraîches. On se délecte de ces douceurs dans un cadre contemporain au luxe discret (assiettes en porcelaine, couverts Christofle), qui est un régal pour les yeux. L\'été, la terrasse sous les arcades offre à vos agapes un décor à la hauteur de l\'assiette. Avis aux amateurs : les petits clafoutis maison aux fruits de saison, offerts avant le café, sont un délice... Royal, c\'est le mot !',	'palais_royal.jpg',	'2017-03-07 01:40:24'),
  (138,	'Cyril Attrazic',	'Aumont-Aubrac',	48130,	NULL,	NULL,	'10 route du Languedoc',	'Un restaurant élégant et bien dans son époque... pour un chef inspiré. Cyril Attrazic signe une belle cuisine créative, franche et expressive, colorée et parfumée, avec de magnifiques produits locaux (telles les viandes de son beau-père). Quant au décor, chic et chaleureux, il ne manque pas de séduire. Vive l\'Aubrac !',	'cyril_attrazic.jpg',	'2017-03-07 01:41:48'),
  (139,	'Auberge de Cassagne',	'Avignon',	84130,	NULL,	NULL,	'450 Allée de Cassagne',	'Poutres, tomettes, cheminée... Dans la tradition de ces auberges bourgeoises dédiées aux plaisirs de la table, le classicisme est ici de mise, de même les produits nobles et certaines recettes plus rustiques. Dans la cave, 700 références privilégient la vallée du Rhône méridionale.',	'auberge_cassagne.jpg',	'2017-03-07 01:43:50'),
  (140,	'La Tour',	'Espalion',	12500,	NULL,	NULL,	'3 Place Saint-Georges',	'Au rez-de-chaussée, traversez le bistrot pour atteindre l\'escalier : le restaurant est à l\'étage ! Là-haut, le chef réalise une cuisine volontiers créative, dans laquelle les saveurs sont toujours au rendez-vous. On se régale dans un cadre élégant et contemporain, propice à la gourmandise...',	'latour.jpg',	'2017-03-07 01:45:09'),
  (141,	'test',	'mareil sur mauldre',	78124,	NULL,	NULL,	'27 rue des fontaines',	'test',	'test-cropped.png',	NULL);

DROP TABLE IF EXISTS `test`;
CREATE TABLE `test` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `text` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;

TRUNCATE `test`;
INSERT INTO `test` (`id`, `text`) VALUES
  (1,	'greg'),
  (2,	'greg');

-- 2017-04-09 17:52:35